services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - mongo
    volumes:
      # Mount source code for hot reloading
      - ./pages:/app/pages
      - ./components:/app/components
      - ./styles:/app/styles
      - ./public:/app/public
      # If you have additional directories, add them here
      # - ./lib:/app/lib
      # - ./utils:/app/utils
    command: npm run dev # Ensure we're using development server

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
